version: '3.8'

services:
  slasher-archive:
    image: ghcr.io/siahmurph/slasher-archive:latest
    container_name: slasher-archive
    restart: unless-stopped
    ports:
      - "8383:80"
    volumes:
      - /opt/appdata/slasher-archive:/app/config
